version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install flask
 
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i7o1w0g9
      - docker build -t patel-flask-app .
      - echo Tagging the Docker image...
      - docker tag patel-flask-app:latest public.ecr.aws/i7o1w0g9/patel-flask-app:latest
      - echo Pushing the Docker image to Amazon ECR...
      - docker push public.ecr.aws/i7o1w0g9/patel-flask-app:latest
      - echo Creating imageDefinitions.json for ECS deployment...
      - echo '[{"name":"patel-flask-app","imageUri":"public.ecr.aws/i7o1w0g9/patel-flask-app:latest"}]' > imageDefinitions.json
 
artifacts:
  files:
    - app.py
    - requirements.txt
    - imageDefinitions.json
